### ISSUE TITLE
Suggestions to improve your code (change variable names and using proper variable types)

### ISSUE THREAD

**Issue by alisepehrnia** [siyavashfeyzi/Shift-Cipher#1]
Hi Siyavash!
I hope you are doing well and enjoying coding!

I have some suggestions to make your code improve:

- It's strongly recommended to use meaningful names for your variables (names that represent the content of variables). I think this list of variables could be the first candidates to change: `p`, `p0`, `c`, `c0`, `ek`, `dk`, `Continue`, `Select`.

- It's better for performance and coding style to use proper variable types based on the value you want to store. For example, you could store "Continue" in a `bool` instead of `int` as it's just storing two values: `0` and `1`.

**Comment by siyavashfeyzi** [comment]
These changes and a few more changes will be implemented soon in version 1.1.
Thanks for paying attention to this repository.

**Comment by alisepehrnia** [comment]
Very good!
It's my pleasure!

**Comment by siyavashfeyzi** [comment]
Done.
